spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    admin-user:
      id: Aditya
      password: Aditya
    webapp:
      enabled: true
    rest:
      enabled: true  

server:
  port: 8079
